name: agent_env
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pip
  - pandas
  - numpy
  - pyarrow
  - jupyterlab=4.4.7
  - ipykernel=6.30.1
  - restrictedpython
  - tqdm
  - ca-certificates
  - certifi
  - openssl

  - pip:
      - torch==2.4.1
      - torchvision==0.19.1
      - torchaudio==2.4.1
      - transformers==4.56.2
      - tokenizers==0.22.1
      - datasets==2.14.7
      - langchain==0.3.27
      - langchain-huggingface==0.3.1
      - langchain-core==0.3.76
      - langgraph==0.6.7
      - langgraph-checkpoint>=2.1.0
      - langsmith==0.4.30
      - huggingface-hub==0.35.1
      - accelerate==1.10.1
      - safetensors==0.6.2
      - anyio
      - httpx
      - python-dotenv
      - ormsgpack>=1.10.0
